Fix a stack on unfreeze with older python interpreters
	Traceback (most recent call last):
	  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1165, in do_action
	    err = call_action(action)
	  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1153, in call_action
	    err = getattr(self, action)()
	  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 5711, in thaw
	    self.master_thaw()
	  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 493, in func
	    func(self)
	  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 5716, in master_thaw
	    self.freezer.thaw()
	  File "/usr/share/opensvc/opensvc/core/freezer.py", line 57, in thaw
	    unlink_and_sync(self.flag)
	  File "/usr/share/opensvc/opensvc/utilities/files/_init.py", line 136, in unlink_and_sync
	    fd = os.open(dirname, os.O_DIRECTORY)
	AttributeError: module 'os' has no attribute 'O_DIRECTORY'

=> fallback to O_RDONLY if the os module does not know about
O_DIRECTORY.