Fix regression on encap stopped resources
The `stopped` value is already available on resource, so
it doesn't need to be computed again.

svc.get_resource(rid, with_encap=True) may return None.
It returns Storage for `encap` that doesn't provide the stopped callable.

This commit fixes the following stack:

    c:monitor | 'NoneType' object is not callable
    Traceback (most recent call last):
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 740, in run
        self.do()
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 814, in do
        self.orchestrator()
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 1466, in orchestrator
        self.resources_orchestrator(path, svc)
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 1667, in resources_orchestrator
        if monitored_resource(svc, rid, resource, smon):
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 1525, in monitored_resource
        if res is None or res.stopped():
    TypeError: 'NoneType' object is not callable